apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: nginx_vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx_vol
      hostPath:
        path: /tmp/hoop

