apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  nodeName: ip-172-31-13-37.ap-south-1.compute.internal
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: nginx-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
      storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/hoop



