apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-alpine
spec:
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: c1
          image: nginx
          resources:
            requests:
              cpu: 50m
              memory: 160Mi
            limits:
              cpu: 100m
              memory: 250Mi




---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: alpine
  port:
    - port: 80
      targetPort: 80



