# deny all egress traffic

apiVersion:  networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-traffic
spec:
  podSelector:
      matchLabels:
        app: netpol
  policyTypes:
    - Ingress
    - Egress
