# deny all egress traffic

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-traffic
  namespace: test-ns
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress