apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netpol
  template:
    metadata:
      labels:
        app: netpol
    spec:
      containers:
        - name: c1
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: net-service
spec:
  selector:
    app: netpol
  ports:
    - port: 80
      targetPort: 80
