apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app1: nginx1
    spec:
      containers:
       - name: c1
         image: chaitu1812/nginx:v2.0.0
         ports:
          - containerPort: 80
            name: nginx
          - containerPort: 80
            name: nginx1

---
apiVersion: v1
kind: Service
metadata:
  name: deploy1-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - targetPort: nginx
      port: 65531



