apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
       - name: c1
         image: chaitu1812/nginx:v1.0.0
         ports:
          - containerPort: 80
            name: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: deploy1-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - targetPort: nginx
      port: 65531



